---
title: "312469083, 308147248, 311605497"
output:
  pdf_document: default
  html_document: default
  word_document: default
---


```{r libraries, include=TRUE,echo=TRUE}
library(fitdistrplus)
library(magrittr)
```

uplode data

```{r}
x <- c(08,
46,
127,
57,
35,
74,
99,
05,
04,
23,
109,
76,
67,
15,
48,
209,
20,
05,
88,
70,
05,
60,
142,
110,
16,
77,
00,
30,
44,
112,
77,
36,
08,
11,
30,
62,
124,
14,
56,
13,
24,
57,
03,
32,
07,
30,
00,
23,
04
)
```

# Fit dist

```{r}
poisFit <- fitdist(x,"pois")
summary(poisFit)
normFit <- fitdist(x,"norm")
summary(normFit)
expFit <- fitdist(x,"exp")
summary(expFit)

```
we can see that the exp distribution is the best because the likelyhood is the higest,  and the "aic" and "bic" is the lowest.


# plot view

```{r}
boxplot(x)
newnormFit<- subset(x, x<150)
print(newnormFit)
newexpFit<- subset(x, x<60)
print(newexpFit)
newpoisFit<- subset(x, x<60)
print(newpoisFit)

```

# new Fit dist - after removing the differents.

```{r}
normFit <- fitdist(newnormFit, "norm")
summary(normFit)
expFit <- fitdist(newexpFit,"exp")
summary(expFit)
poisFit <- fitdist(newpoisFit, "pois")
summary(poisFit)

```
we can see that the exp distribution is the best because the likelyhood is the higest,  and the "aic" and "bic" is the lowest.


# Goodness of fit


```{r}
gofstat(expFit)
expFit <- gofstat(expFit)%>%print()
expFit$kstest%>%print()
mean (newexpFit)
```
